### ISSUE TITLE
opennzippline contracts not importing

### ISSUE THREAD

**Issue by HARSHisawesome2** [tronprotocol/tronbox#150]
hello when i try to deploy my contract for minting NFTS via trc20 but while compile gives these errors why pls help out 👍 

PS C:\Users\bq562ts\Downloads\TRONDEV - Copy\res> tronbox compile
Error: Could not find @openzeppelin/contracts/token/ERC20/IERC20.sol from any sources; imported from C:/Users/bq562ts/Downloads/TRONDEV - Copy/res/contracts/DICE.sol
    at C:\Users\bq562ts\AppData\Roaming\npm\node_modules\tronbox\build\components\Resolver\index.js:1:1707
    at C:\Users\bq562ts\AppData\Roaming\npm\node_modules\tronbox\node_modules\async\internal\onlyOnce.js:12:16
    at next (C:\Users\bq562ts\AppData\Roaming\npm\node_modules\tronbox\node_modules\async\whilst.js:68:18)
    at C:\Users\bq562ts\AppData\Roaming\npm\node_modules\tronbox\build\components\Resolver\index.js:1:1495
    at C:\Users\bq562ts\AppData\Roaming\npm\node_modules\tronbox\build\components\Resolver\fs.js:1:1685
    at C:\Users\bq562ts\AppData\Roaming\npm\node_modules\tronbox\node_modules\async\internal\once.js:12:16
    at replenish (C:\Users\bq562ts\AppData\Roaming\npm\node_modules\tronbox\node_modules\async\internal\eachOfLimit.js:61:25)
    at iterateeCallback (C:\Users\bq562ts\AppData\Roaming\npm\node_modules\tronbox\node_modules\async\internal\eachOfLimit.js:50:17)
    at C:\Users\bq562ts\AppData\Roaming\npm\node_modules\tronbox\node_modules\async\internal\onlyOnce.js:12:16
    at ReadFileContext.callback (C:\Users\bq562ts\AppData\Roaming\npm\node_modules\tronbox\build\components\Resolver\fs.js:1:1629)

**Comment by HARSHisawesome2** [comment]
please help @llwslc

**Comment by llwslc** [comment]
Did you install the dependency package?

```
npm install @openzeppelin/contracts
```

**Comment by HARSHisawesome2** [comment]
checking  ..
