### ISSUE TITLE
trontools/quickstart : UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'privateKeys' of undefined

### ISSUE THREAD

**Issue by prasad-kumkar** [tronprotocol/tronbox#157]
Finding this issue while running tron locally
System: Mac M1 Max
Ram: 64GB
Version: latest

<img width="1010" alt="image" src="https://user-images.githubusercontent.com/43164022/194821596-a9560ae6-c669-4f95-ac6e-78f6da25319a.png">

```The "chunk" argument must be one of type string or Buffer. Received type object

(node:108) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'privateKeys' of undefined

    at flatAccounts (/tron/app/src/routes/admin.js:15:37)

    at getBalances (/tron/app/src/routes/admin.js:27:21)

    at /tron/app/src/routes/admin.js:127:26

    at Layer.handle [as handle_request] (/tron/app/node_modules/express/lib/router/layer.js:95:5)

    at next (/tron/app/node_modules/express/lib/router/route.js:137:13)

    at Route.dispatch (/tron/app/node_modules/express/lib/router/route.js:112:3)

    at Layer.handle [as handle_request] (/tron/app/node_modules/express/lib/router/layer.js:95:5)

    at /tron/app/node_modules/express/lib/router/index.js:281:22

    at Function.process_params (/tron/app/node_modules/express/lib/router/index.js:335:12)

    at next (/tron/app/node_modules/express/lib/router/index.js:275:10)

(node:108) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

(node:108) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by llwslc** [comment]
You will need to generate accounts. Please refer to this link.

https://github.com/TRON-US/docker-tron-quickstart/blob/master/README.md#more-accounts
