### ISSUE TITLE
Cannot install tronbox

### ISSUE THREAD

**Issue by ruzpuz** [tronprotocol/tronbox#41]
Hi, I am trying to install tronbox on my machine and things are not doing so good for me. 

I have a fresh install of MacOS

```
System Software Overview:

  System Version:	macOS 10.15.1 (19B88)
  Kernel Version:	Darwin 19.0.0
  Boot Volume:	Macintosh HD
  Boot Mode:	Normal
```

And node things:

```
zeus:~ vladar$ npm -v
6.12.1
zeus:~ vladar$ node -v
v13.1.0
zeus:~ vladar$ node-gyp -v
v6.0.1
```

But when I try to install tronbox it fails for some reason. This looks like some permission failure but I am really unaware what could it be? Did you guys see something like it before? 

Full error log:

```
zeus:~ vladar$ sudo npm install -g tronbox

npm WARN deprecated fsevents@1.2.9: One of your dependencies needs to upgrade to fsevents v2: 1) Proper nodejs v10+ support 2) No more fetching binaries from AWS, smaller package size
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm WARN deprecated truffle-contract@4.0.30: WARNING: This package has been renamed to @truffle/contract.
npm WARN deprecated truffle-contract-schema@3.0.13: WARNING: This package has been renamed to @truffle/contract-schema.
npm WARN deprecated truffle-interface-adapter@0.2.5: WARNING: This package has been renamed to @truffle/interface-adapter.
npm WARN deprecated truffle-blockchain-utils@0.0.10: WARNING: This package has been renamed to @truffle/blockchain-utils.
npm WARN deprecated truffle-error@0.0.5: WARNING: This package has been renamed to @truffle/error.
npm WARN deprecated core-js@2.6.10: core-js@<3.0 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated truffle-config@1.1.20: WARNING: This package has been renamed to @truffle/config.
npm WARN deprecated truffle-provider@0.1.16: WARNING: This package has been renamed to @truffle/provider.
/usr/local/bin/tronbox -> /usr/local/lib/node_modules/tronbox/build/tronbox.js

> fsevents@1.2.9 install /usr/local/lib/node_modules/tronbox/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Pre-built binaries not installable for fsevents@1.2.9 and node@13.1.0 (node-v79 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/usr/local/lib/node_modules/tronbox/node_modules/fsevents/lib' 
gyp WARN EACCES current user ("nobody") does not have permission to access the dev dir "/Users/vladar/Library/Caches/node-gyp/13.1.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/tronbox/node_modules/fsevents/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/tronbox/node_modules/fsevents/.node-gyp'
gyp ERR! System Darwin 19.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/local/lib/node_modules/tronbox/node_modules/fsevents/lib/binding/Release/node-v79-darwin-x64/fse.node" "--module_name=fse" "--module_path=/usr/local/lib/node_modules/tronbox/node_modules/fsevents/lib/binding/Release/node-v79-darwin-x64" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v79"
gyp ERR! cwd /usr/local/lib/node_modules/tronbox/node_modules/fsevents
gyp ERR! node -v v13.1.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/tronbox/node_modules/fsevents/lib/binding/Release/node-v79-darwin-x64/fse.node --module_name=fse --module_path=/usr/local/lib/node_modules/tronbox/node_modules/fsevents/lib/binding/Release/node-v79-darwin-x64 --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v79' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/tronbox/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1028:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Darwin 19.0.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/tronbox/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/tronbox/node_modules/fsevents
node-pre-gyp ERR! node -v v13.1.0
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/tronbox/node_modules/fsevents/lib/binding/Release/node-v79-darwin-x64/fse.node --module_name=fse --module_path=/usr/local/lib/node_modules/tronbox/node_modules/fsevents/lib/binding/Release/node-v79-darwin-x64 --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v79' (1)

> keccak@2.0.0 install /usr/local/lib/node_modules/tronbox/node_modules/keccak
> npm run rebuild || echo "Keccak bindings compilation fail. Pure JS implementation will be used."


> keccak@2.0.0 rebuild /usr/local/lib/node_modules/tronbox/node_modules/keccak
> node-gyp rebuild

gyp WARN EACCES current user ("nobody") does not have permission to access the dev dir "/Users/vladar/Library/Caches/node-gyp/13.1.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/tronbox/node_modules/keccak/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/tronbox/node_modules/keccak/.node-gyp'
gyp ERR! System Darwin 19.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/tronbox/node_modules/keccak
gyp ERR! node -v v13.1.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keccak@2.0.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keccak@2.0.0 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Keccak bindings compilation fail. Pure JS implementation will be used.

> secp256k1@3.7.1 install /usr/local/lib/node_modules/tronbox/node_modules/secp256k1
> npm run rebuild || echo "Secp256k1 bindings compilation fail. Pure JS implementation will be used."


> secp256k1@3.7.1 rebuild /usr/local/lib/node_modules/tronbox/node_modules/secp256k1
> node-gyp rebuild

gyp WARN EACCES current user ("nobody") does not have permission to access the dev dir "/Users/vladar/Library/Caches/node-gyp/13.1.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/tronbox/node_modules/secp256k1/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/tronbox/node_modules/secp256k1/.node-gyp'
gyp ERR! System Darwin 19.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/tronbox/node_modules/secp256k1
gyp ERR! node -v v13.1.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! secp256k1@3.7.1 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the secp256k1@3.7.1 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Secp256k1 bindings compilation fail. Pure JS implementation will be used.

> sha3@1.2.3 install /usr/local/lib/node_modules/tronbox/node_modules/sha3
> node-gyp rebuild

gyp WARN EACCES current user ("nobody") does not have permission to access the dev dir "/Users/vladar/Library/Caches/node-gyp/13.1.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/tronbox/node_modules/sha3/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/tronbox/node_modules/sha3/.node-gyp'
gyp ERR! System Darwin 19.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/tronbox/node_modules/sha3
gyp ERR! node -v v13.1.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/tronbox/node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sha3@1.2.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sha3@1.2.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/vladar/.npm/_logs/2019-11-18T15_03_31_416Z-debug.log
```

**UPDATE 1**

I managed to pass this by manually fixing privileges for `/usr/local/lib/node_modules/` folder. Not sure why is this being installed as a user `nobody` but ok. Next error i got was that options.uid should be of type int32. This is a super weird message I have never previously seen. 

```
npm ERR! code ERR_INVALID_ARG_TYPE
npm ERR! The "options.uid" property must be of type int32. Received type number
```

**UPDATE 2**

I can confirm that this issue happens with LTS Node as well

```
zeus:~ vladar$ node -v
v12.13.0
zeus:~ vladar$ npm -v
6.12.0
```

**Comment by sullof** [comment]
That is a permission issue. It looks like you installed node as root. I suggest to use NVM to install node. Anyway, did you try sudoing the install?

**Comment by dev0000001** [comment]
I fixed it by: sudo -i
Then I ran npm i -g tronbox

**Comment by ruzpuz** [comment]
unfortunately I just tried this (on a fresh mac os) and it did not work 

```
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/web3-js/WebSocket-Node.git
npm ERR! 
npm ERR! fatal: Unable to read current working directory: Permission denied
npm ERR! 
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/root/.npm/_logs/2021-04-14T10_26_56_878Z-debug.log
```
