### ISSUE TITLE
TronBox v2.7.9 Error Cannot find Module '.'

### ISSUE THREAD

**Issue by sjaiswal17** [tronprotocol/tronbox#47]
When you install tronbox@2.7.9 and hit tronbox command in your cli it will give you this error

```cmd
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '.'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/rails/.nvm/versions/node/v10.15.1/lib/node_modules/tronbox/build/tronbox.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

**Comment by modvili** [comment]
I too have the same issue when running the "npm i tronbox -g" on a macos 10.15.
I already tried different node versions but without any success. 

Any help is greatly appreciated.

**Comment by maxisacoder** [comment]
same

**Comment by modvili** [comment]
It looks like this issue has been solved with the version 2.7.10

**Comment by sullof** [comment]
Yes, I solved it before leaving Tron :-)

**Comment by modvili** [comment]
> Yes, I solved it before leaving Tron :-)

Thank you for your hard work and good luck with your next challenge.
