### ISSUE TITLE
Migration error: no such file or directory

### ISSUE THREAD

**Issue by Madeindreams** [tronprotocol/tronbox#69]
I have set a directory for my project contract and json in tronbox.js

```
     contracts_directory: './src/contracts',
     contracts_build_directory: './src/abis',
```

I can compile without issues and the files are placed in the right directories.

However when i want tu run a migration with this command

source .env && tronbox migrate --network shasta

I get the following error;

Using network 'shasta'.

```
Running migration: 1_initial_migration.js
internal/fs/utils.js:308
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir './src/abis'
    at Object.readdirSync (fs.js:1021:3)
    at FS.getContractName (/home/idecentralize/.nvm/versions/node/v14.14.0/lib/node_modules/tronbox/build/components/Resolver/fs.js:1:904)
    at FS.require (/home/idecentralize/.nvm/versions/node/v14.14.0/lib/node_modules/tronbox/build/components/Resolver/fs.js:1:440)
    at Resolver.require (/home/idecentralize/.nvm/versions/node/v14.14.0/lib/node_modules/tronbox/build/components/Resolver/index.js:1:740)
    at Object.require (/home/idecentralize/.nvm/versions/node/v14.14.0/lib/node_modules/tronbox/build/components/Migrate/index.js:1:5238)
    at ResolverIntercept.require (/home/idecentralize/.nvm/versions/node/v14.14.0/lib/node_modules/tronbox/build/components/Migrate/resolverintercept.js:1:278)
    at /mnt/d/Code/tronx/migrations/1_initial_migration.js:1:28
    at Script.runInContext (vm.js:142:18)
    at Script.runInNewContext (vm.js:147:17)
    at Object.file (/home/idecentralize/.nvm/versions/node/v14.14.0/lib/node_modules/tronbox/build/components/Require.js:1:1438)

```
How can I resolve this. All the files are in the right place.

**Comment by Madeindreams** [comment]
Since I'm on windows under WSL I guess I had to provide the full path and not just the path relative to the project. So I changed my path to the full path

```
     contracts_directory: '/mnt/d/code/tronx/src/contracts',
     contracts_build_directory: '/mnt/d/code/tronx/src/abis',
```

And that solved it.
