### ISSUE TITLE
Error: Error parsing D:/.../ConvertLib.sol

### ISSUE THREAD

**Issue by Megpoid** [tronprotocol/tronbox#82]
: Cannot find module 'C:\Users\Device-4\.tronbox\solc\soljson_v0.5.4.js'
Require stack:
- C:\Users\Device-4\AppData\Roaming\npm\node_modules\tronbox\build\components\TronSolc.js
- C:\Users\Device-4\AppData\Roaming\npm\node_modules\tronbox\build\lib\commands\version.js
- C:\Users\Device-4\AppData\Roaming\npm\node_modules\tronbox\build\lib\commands\index.js
- C:\Users\Device-4\AppData\Roaming\npm\node_modules\tronbox\build\index.js
- C:\Users\Device-4\AppData\Roaming\npm\node_modules\tronbox\build\tronbox.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at getWrapper (C:\Users\Device-4\AppData\Roaming\npm\node_modules\tronbox\build\components\TronSolc.js:1:2377)
    at Object.parseImports (C:\Users\Device-4\AppData\Roaming\npm\node_modules\tronbox\build\components\Compile\parser.js:1:2359)
    at C:\Users\Device-4\AppData\Roaming\npm\node_modules\tronbox\build\components\Compile\profiler.js:1:4981
    at C:\Users\Device-4\AppData\Roaming\npm\node_modules\tronbox\build\components\Resolver\index.js:1:1727
    at C:\Users\Device-4\AppData\Roaming\npm\node_modules\tronbox\node_modules\async\internal\onlyOnce.js:12:16
    at next (C:\Users\Device-4\AppData\Roaming\npm\node_modules\tronbox\node_modules\async\whilst.js:68:18)

am i missing something? i'm pretty sure follow the order

**Comment by llwslc** [comment]
Can describe the details of your operation?

**Comment by folowing** [comment]
may be you should try to run `tronbox --download-compiler 0.5.4` again then rer-un `tronbox compile`.
