### ISSUE TITLE
tronbox console | accounts and contract address details | connected with docker run -it -p 9090:9090 --rm --name tron trontools/quickstart

### ISSUE THREAD

**Issue by guru260** [tronprotocol/tronbox#98]
**1. How to get accounts in tronbox console**
```
truffle console
truffle(development)> accounts
[ '0xd905A5eee0cA8E089E58B9b1192FBdd05dB45b10',
  '0x2b9e76dD2CC9d566d43EB7668AcD5eCDa6f38F2C',
  '0xEcd469B022caD7A683E0BB439BA3AEa0b4F55469',
  '0xF7Dc20DFF665f7d4E7515111B4Fae3843479B9a6',
  '0xd3bd1Cd6D6B7E32c10B760e754A89Cf546BB172e',
  '0xef230314ddDE21d52182eBA459639268a86d1b61',
  '0x2623e3C37cb6C7115284Ef1F13547E8085086EB3',
  '0x834c6FD5bCfbc4fe0C41748C518B08Ee04496F96',
  '0x7f73aFe4ddbba03A91139741C05Eb2F96448c321',
  '0xD807Fd7Bb238113D15C573841ECeffe619CC6574' ]
```
How to get the same in tronbox console. I am getting accounts is not defined error in tronbox console.
```
 tronbox console
tronbox(development)> accounts
ReferenceError: accounts is not defined
```
**2. How to get contract address in tronbox console**
I can get the contract address in truffle like the following, 
```
truffle(development)> let instance = await Sample.deployed()
truffle(development)> instance.address
'0x7C4c67EddDd8eDe8c3c8548195DA16885A75eEc5'
```
But the same is not working in tronbox.
```
tronbox(development)> let instance = await Sample.deployed()
SyntaxError: await is only valid in async function
    at REPLServer.Interface._onLine (readline.js:280:10)
    at REPLServer.emit (events.js:211:7)
    at emitOne (events.js:116:13)
    at REPLServer.onLine (repl.js:468:10)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at bound (domain.js:301:14)
    at ReplManager.interpret (/home/css/.nvm/versions/node/v8.16.2/lib/node_modules/tronbox/build/lib/repl.js:1:1807)
    at Console.interpret (/home/css/.nvm/versions/node/v8.16.2/lib/node_modules/tronbox/build/lib/console.js:1:3182)
    at Object.runInContext (vm.js:119:10)
    at createScript (vm.js:80:10)
tronbox(development)> let instance =  Sample.deployed()
TypeError: Cannot read property 'match' of undefined
    at REPLServer.onLine (repl.js:468:10)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at bound (domain.js:301:14)
    at ReplManager.interpret (/home/css/.nvm/versions/node/v8.16.2/lib/node_modules/tronbox/build/lib/repl.js:1:1807)
    at Console.interpret (/home/css/.nvm/versions/node/v8.16.2/lib/node_modules/tronbox/build/lib/console.js:1:2864)
    at Command.getCommand (/home/css/.nvm/versions/node/v8.16.2/lib/node_modules/tronbox/build/lib/command.js:1:376)
    at Object.Yargs.self.parse (/home/css/.nvm/versions/node/v8.16.2/lib/node_modules/tronbox/node_modules/yargs/yargs.js:532:23)
    at Object.Yargs.self._parseArgs (/home/css/.nvm/versions/node/v8.16.2/lib/node_modules/tronbox/node_modules/yargs/yargs.js:938:27)
    at Function.Parser.detailed (/home/css/.nvm/versions/node/v8.16.2/lib/node_modules/tronbox/node_modules/yargs/node_modules/yargs-parser/index.js:761:10)
    at parse (/home/css/.nvm/versions/node/v8.16.2/lib/node_modules/tronbox/node_modules/yargs/node_modules/yargs-parser/index.js:125:13)

```

**Comment by llwslc** [comment]
Thanks, We will support this feature as soon as possible
